common: &common
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000
  username: saasbook
  password: cobra666 # from psql setup, see Postgresql

development:
  <<: *common
  database: TestAppRailsTurtorial

test:
  <<: *common
  database: TestAppRailsTurtorial_test

production:
  <<: *common
  database: TestAppRailsTurtorial
